# NumPy Module

In [83]:
# NumPy, an acronym for Numerical Python, is a package to perform scientific
# computing in Python efficiently. It includes random number generation
# capabilities, functions for basic linear algebra, Fourier transforms as well
# as a tool for integrating Fortran and C/C++ code along with a bunch of
# other functionalities.

In [84]:
# NumPy is an open-source project and a successor to two earlier scientific
# Python libraries: Numeric and Numarray.

In [85]:
# It can be used as an efficient multi-dimensional container of generic
# data. This allows NumPy to integrate with a wide variety of databases
# seamlessly. It also features a collection of routines for processing single and
# multidimensional vectors known as arrays in programming parlance.

In [86]:
# NumPy is not a part of the Python Standard Library and hence, as with
# any other such library or module, it needs to be installed on a workstation
# before it can be used. Based on the Python distribution one uses, it can
# be installed via a command prompt, conda prompt, or terminal using the
# following command. One point to note is that if we use the Anaconda distri-
# bution to install Python, most of the libraries (like NumPy, pandas, scikit-learn,
# matplotlib, etc. ) used in the scientific Python ecosystem come pre-installed.

# # pip install numpy

# Note: If we use the Python or iPython console to install the NumPy library, the command to install it 
# would be preceded by the character!

In [87]:
# Once installed we can use it by importing into our program by using the import statement. The de facto way of importing 
# is shown below:

# # import numpy as np

# Here, the NumPy library is imported with an alias of np so that any functionality within it can be used with convenience.
# We will be using this form of alias for all examples in this section.

# 10.1 NumPy Arrays

In [89]:
# A Python list is a pretty powerful sequential data structure with some nifty
# features. For example, it can hold elements of various data types which
# can be added, changed or removed as required. Also, it allows index sub-
# setting and traversal. But lists lack an important feature that is needed
# while performing data analysis tasks. We often want to carry out operations
# over an entire collection of elements, and we expect Python to perform this
# fast. With lists executing such operations over all elements efficiently is a
# problem. For example, let’s consider a case where we calculate PCR (Put
# Call Ratio) for the previous 5 days. Say, we have put and call options vol-
# ume (in Lacs) stored in lists call_vol and put_vol respectively. We then
# compute the PCR by dividing put volume by call volume as illustrated in
# the below script:

In [88]:
# put volume in lacs
put_vol = [52.89, 45.14, 63.84, 77.1, 74.6]

# call volume in lacs
call_vol = [49.51, 50.45, 59.11, 80.49, 65.11]

# Computing Put Call Ratio (PCR)
put_vol / call_vol

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
# Unfortunately, Python threw an error while calculating PCR values as it
# has no idea on how to do calculations on lists. We can do this by iterating
# over each item in lists and calculating the PCR for each day separately.
# However, doing so is inefficient and tiresome too. A way more elegant
# solution is to use NumPy arrays, an alternative to the regular Python list.

In [ ]:
# The NumPy array is pretty similar to the list, but has one useful feature: we
# can perform operations over entire arrays(all elements in arrays). It’s easy
# as well as super fast. Let us start by creating a NumPy array. To do this,
# we use array() function from the NumPy package and create the NumPy
# version of put_vol and call_vol lists.

In [ ]:
# Importing NumPy library
import numpy as np

# Creating arrays
n_put_vol = np.array(put_vol)
n_call_vol = np.array(call_vol)

n_put_vol

array([52.89, 45.14, 63.84, 77.1 , 74.6 ])

In [ ]:
n_call_vol

array([49.51, 50.45, 59.11, 80.49, 65.11])

In [ ]:
# Here, we have two arrays n_put_vol and n_call_vol which holds put and
# call volume respectively. Now, we can calculate PCR in one line:

# Computing Put Call Ratio (PCR)
pcr = n_put_vol / n_call_vol

pcr

array([1.06826904, 0.89474727, 1.0800203 , 0.95788297, 1.14575334])

In [ ]:
# This time it worked, and calculations were performed element-wise. The
# first observation in pcr array was calculated by dividing the first element
# in n_put_vol by the first element in n_call_vol array. The second element
# in pcr was computed using the second element in the respective arrays
# and so on.

In [ ]:
# First, when we tried to compute PCR with regular lists, we got an error, be-
# cause Python cannot do calculations with lists like we want it to. Then
# we converted these regular lists to NumPy arrays and the same opera-
# tion worked without any problem. NumPy work with arrays as if they
# are scalars. But we need to pay attention here. NumPy can do this easily
# because it assumes that array can only contain values of a single type. It’s
# either an array of integers, floats or booleans and so on. If we try to cre-
# ate an array of different types like the one mentioned below, the resulting
# NumPy array will contain a single type only. String in the below case:

np.array([1, 'Python', True])

array(['1', 'Python', 'True'], dtype='<U21')

In [ ]:
# NOTE : NumPy arrays are made to be created as homogeneous
# arrays, considering the mathematical operations that can be per-
# formed on them. It would not be possible with heterogeneous
# data sets.

In [ ]:
# In the example given above, an integer and a boolean were both converted
# to strings. NumPy array is a new type of data structure type like the Python
# list type that we have seen before. This also means that it comes with its
# own methods, which will behave differently from other types. Let us im-
# plement the + operation on the Python list and NumPy arrays and see how
# they differ.

In [ ]:
# Creating lists
list_1 = [1, 2, 3]
list_2 = [5, 6, 4]

# Adding two lists
list_1 + list_2

[1, 2, 3, 5, 6, 4]

In [ ]:
# Creating arrays
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([5, 6, 4])

# Adding two arrays
arr_1 + arr_2

array([6, 8, 7])

In [ ]:
# As can be seen in the above example, performing the + operation with
# list_1 and list_2, the list elements are pasted together, generating a list
# with 6 elements. On the other hand, if we do this with NumPy arrays,
# Python will do an element-wise sum of the arrays.

# 10.1.1 N-dimensional arrays

In [ ]:
# Until now we have worked with two arrays: n_put_vol and n_call_vol. If
# we are to check its type using type(), Python tells us that they are of type
# numpy.ndarray as shown below:

# Checking array type
type(n_put_vol)

numpy.ndarray

In [ ]:
# Based on the output we got, it can be inferred that they are of data type
# ndarray which stands for n-dimensional array within NumPy. These arrays
# are one-dimensional arrays, but NumPy also allows us to create two dimen-
# sional, three dimensional and so on. We will stick to two dimensional for
# our learning purpose in this module. We can create a 2D (two dimensional)
# NumPy array from a regular Python list of lists. Let us create one array for
# all put and call volumes.

In [ ]:
# Recalling put and call volumes lists
put_vol

[52.89, 45.14, 63.84, 77.1, 74.6]

In [ ]:
call_vol

[49.51, 50.45, 59.11, 80.49, 65.11]

In [ ]:
# Creating a two-dimensional array
n_2d = np.array([put_vol, call_vol])
n_2d

array([[52.89, 45.14, 63.84, 77.1 , 74.6 ],
       [49.51, 50.45, 59.11, 80.49, 65.11]])

In [ ]:
# We see that n_2d array is a rectangular data structure. Each list pro-
# vided in the np.array creation function corresponds to a row in the two-
# dimensional NumPy array. Also for 2D arrays, the NumPy rule applies: an
# array can only contain a single type. If we change one float value in the
# above array definition, all the array elements will be coerced to strings, to
# end up with a homogeneous array. We can think of a 2D array as an ad-
# vanced version of lists of a list. We can perform element-wise operation
# with 2D as we had seen for a single dimensional array.

# 10.2 Array creation using built-in functions

In [ ]:
# An explicit input has been provided while creating n_call_vol and
# n_put_vol arrays. In contrast, NumPy provides various built-in functions
# to create arrays and input to them will be produced by NumPy. Below we
# discuss a handful of such functions:

In [ ]:
# zeros(shape, dtype=float) returns an array of a given shape and
# type, filled with zeros. If the dtype is not provided as an input, the
# default type for the array would be float.

In [ ]:
import numpy as np

In [ ]:
# Creating a one-dimensional array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# Creating a two-dimensional array
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Creating a one-dimensional array of integer type
np.zeros(5, dtype= int)

array([0, 0, 0, 0, 0])

In [ ]:
# ones(shape, dtype= float) returns an array of a given shape and type, filled with ones. 
# If dtype is not provided as an input, the default type for the array would be float.

In [ ]:
# Creating a one-dimensional array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# Creating a one-dimensional array of integer type
np.ones(5, dtype= int)

array([1, 1, 1, 1, 1])

In [ ]:
# full(shape, fill_value, dtype= None) returns an array of a given shape and type, 
# fill with fill_value given in input parameters.

In [ ]:
# Creating a one-dimensional array with value as 12
np.full(5, 12)

array([12, 12, 12, 12, 12])

In [ ]:
# Creating a one-dimensional array with value as 12
np.full((2, 3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
# arange([start, ]stop, [step]) returns an array with evenly
# spaced values within a given interval. Here the start and step param-
# eters are optional. If they are provided NumPy will consider them
# while computing the output. Otherwise, range computation starts
# from 0. For all cases, stop value will be excluded in the output.

In [ ]:
# Creating an array with only stop argument
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
# Creating an array with start and stop arguments
np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [ ]:
# Creating an array with given interval and step value as 0.5
np.arange(3, 8, 0.5)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [ ]:
# linspace(start, stop, num=50, endpoint=True) returns evenly
# spaced numbers over a specified interval. The number of samples
# to be returned is specified by the num parameter. The endpoint of the
# interval can optionally be excluded.

In [ ]:
# Creating an evenly spaced array with five numbers within
# interval 2 to 3
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
# Creating an array excluding end value
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
# Creating an array with ten values within the specified interval
np.linspace(11, 20, num=10)

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

# 10.3 Random Sampling in NumPy

In [ ]:
# In addition to built-in functions discussed above, we have a random sub-
# module within the NumPy that provides handy functions to generate data
# randomly and draw samples from various distributions. Some of the
# widely used such functions are discussed here.

In [ ]:
# rand([d0, d1, ..., dn]) is used to create an array of a given shape
# and populate it with random samples from a uniform distribution over
# [0, 1). It takes only positive arguments. If no argument is provided,
# a single float value is returned.

In [ ]:
# Generated single random number
np.random.rand()

0.26791944329962647

In [ ]:
# Generating a one-dimensional array with four random values
np.random.rand(4)

array([0.39483532, 0.49911609, 0.05620498, 0.56357015])

In [ ]:
# Generating a two-dimensional array
np.random.rand(2, 3)

array([[0.52927428, 0.81157128, 0.35037124],
       [0.57447097, 0.43755264, 0.4870666 ]])

In [ ]:
# randn([d0, d1, ..., dn]) is used to create an array of the given
# shape and populate it with random samples from a standard normal
# distributions. It takes only positive arguments and generates an ar-
# ray of shape (d0, d1, ..., dn) filled with random floats sampled
# from a univariate normal distribution of mean 0 and variance 1. If
# no argument is provided, a single float randomly sampled from the
# distribution is returned.

In [ ]:
# Generating a random sample
np.random.randn()

1.1186134492185638

In [ ]:
# Generating a two-dimensional array over N(0, 1)
np.random.randn(2, 3)

array([[-0.62514104, -0.42623826,  0.08744184],
       [-0.21471799,  0.56173377, -0.68651587]])

In [ ]:
# Generating a two-dimensional array over N(3, 2.25)
1.5 * np.random.randn(2, 3) + 3

array([[0.79077225, 0.72728173, 4.04497893],
       [2.59684037, 4.30974112, 6.2259094 ]])

In [ ]:
# randint(low, high=None, size=None) returns a random integer
# from a discrete uniform distribution with limits of low (inclusive) and
# high (exclusive). If high is None (the default), then results are from 0
# to low. If the size is specified, it returns an array of the specified size.

In [ ]:
# Generating a random integer between 0 and 6
np.random.randint(6, 9)

7

In [ ]:
# Generating a one-dimensional array with values between 3 and 9
np.random.randint(3, 9, size=5)

array([3, 7, 4, 7, 4])

In [ ]:
# Generating a two-dimensional array with values between 3 and 9
np.random.randint(3, 9, size=(2, 5))

array([[3, 7, 3, 7, 7],
       [5, 8, 5, 3, 4]])

In [ ]:
# random(size= None) returns a random float value between 0 and 1 which is drawn from the continuous uniform distribution.

# Generating a random float
np.random.random()

0.6647452902317377

In [ ]:
# Generating a one-dimensional array
np.random.random(3)

array([0.19732981, 0.05407799, 0.10462027])

In [ ]:
# Generating a two-dimensional array
np.random.random((3, 2))

array([[0.79954293, 0.21986599],
       [0.24765303, 0.69261002],
       [0.88887064, 0.25671919]])

In [ ]:
# binomial(n, p, size=None) returns samples drawn from a binomial
# distribution with n trials and p probability of success where n is
# greater than 0 and p is in the interval of 0 and 1.

In [ ]:
# Number of trials, probability of each trial
n, p = 1, .5

In [ ]:
# Flipping a coin 1 time for 50 times
samples = np.random.binomial(n, p, 50)
samples

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1])

In [ ]:
# normal(mu=0.0, sigma=1.0, size=None) draws random samples
# from a normal (Gaussian) distribution. If no arguments provided, a
# sample will be drawn from N(0, 1).

In [ ]:
# Initialize mu and sigma
mu, sigma = 0, 0.1

In [ ]:
# Drawing 5 samples in a one-dimensional array
np.random.normal(mu, sigma, 5)

array([-0.02228195, -0.22987121,  0.12097913,  0.22561973,  0.00547722])

In [ ]:
# Drawing 10 samples in a two-dimensional array of shape (2, 5)
np.random.normal(mu, sigma, (2, 5))

array([[-0.15964562, -0.10294193, -0.08267347, -0.01824829, -0.03777221],
       [ 0.10762057,  0.13743631, -0.11737602,  0.02130311,  0.13789648]])

In [ ]:
# uniform(low=0.0, high=1.0, size=None) draws samples from a
# uniform distribution over the interval 0 (including) and 1 (excluding),
# if no arguments are provided. In other words, any value drawn is
# equally likely within the interval.

In [ ]:
# Creating a one-dimensional array with samples drawn within [-1, 0)
np.random.uniform(-1, 0, 10)

array([-0.30567842, -0.01770339, -0.47054152, -0.25987772, -0.32227457,
       -0.21989057, -0.6040749 , -0.31867413, -0.69462102, -0.3730445 ])

In [ ]:
# Creating a two-dimensional array with samples drawn within [0, 1)
np.random.uniform(size=(5, 2))

array([[0.52143119, 0.38338293],
       [0.33505819, 0.36311708],
       [0.6283989 , 0.01638512],
       [0.79169372, 0.46725573],
       [0.74667709, 0.90470879]])

In [ ]:
# In addition to functions shown above, we can draw samples from vari-
# ous other distributions such as Poisson, Gamma, Exponential, etc. using
# NumPy.

# 10.4 Array Attributes and Methods

In [ ]:
# We now have some idea about the working of NumPy arrays. Let us now
# explore the functionalities provided by them. As with any Python object,
# NumPy arrays also have a rich set of attributes and methods which sim-
# plifies the data analysis process to a great extent. Following are the most
# useful array attributes. For illustration purpose, we will be using previ-
# ously defined arrays.

In [115]:
# ndim attribute displays the number of dimensions of an array. Using
# this attribute on n_call_vol and pcr, we expect dimensions to be 1
# and 2 respectively. Let’s check.

# Importing NumPy library
import numpy as np

# Creating arrays
n_put_vol = np.array(put_vol)
n_call_vol = np.array(call_vol)

In [117]:
# put volume in lacs
put_vol = [52.89, 45.14, 63.84, 77.1, 74.6]

# call volume in lacs
call_vol = [49.51, 50.45, 59.11, 80.49, 65.11]

In [114]:
# Checking dimensions for n_put_vol array
n_put_vol.ndim

1

In [112]:
# Checking dimensions for n_call_vol array
n_call_vol.ndim

1

In [110]:
# Creating a two-dimensional array
n_2d = np.array([put_vol, call_vol])
n_2d

array([[52.89, 45.14, 63.84, 77.1 , 74.6 ],
       [49.51, 50.45, 59.11, 80.49, 65.11]])

In [113]:
n_2d.ndim

2

In [116]:
# shape returns a tuple with the dimensions of the array. 
# It may also be used to reshape the array in-place by assigning a tuple of array dimensions to it.

# Checking the shape of the one-dimensional array
n_put_vol.shape 

(5,)

In [118]:
# Checking shape of the two-dimensional array
n_2d.shape

(2, 5)

In [119]:
# Printing n_2d with 2 rows and 5 columns
n_2d

array([[52.89, 45.14, 63.84, 77.1 , 74.6 ],
       [49.51, 50.45, 59.11, 80.49, 65.11]])

In [120]:
# Reshaping n_2d using the shape attribute
n_2d.shape = (5, 2)

In [121]:
# Printing reshaped array
n_2d

array([[52.89, 45.14],
       [63.84, 77.1 ],
       [74.6 , 49.51],
       [50.45, 59.11],
       [80.49, 65.11]])

In [122]:
# size returns the number of elements in the array
n_call_vol.size

5

In [123]:
n_2d.size

10

In [124]:
# dtype returns the data-type of the array’s elements. As we learned
# above, NumPy comes with its own data type just like regular built-in
# data types such as int, float, str, etc.

In [125]:
n_put_vol.dtype

dtype('float64')

In [ ]:
# A typical first step in analyzing a data is getting to the data in the first
# place. In an ideal data analysis process, we generally have thousands of
# numbers which need to be analyzed. Simply staring at these numbers
# won’t provide us with any insights. Instead, what we can do is generate
# summary statistics of the data. Among many useful features, NumPy
# also provides various statistical functions which are good to perform such
# statistics on arrays.

In [126]:
# Let us create a samples array and populate it with samples drawn from
# a normal distribution with a mean of 5 and standard deviation of 1.5 and
# compute various statistics on it.

In [127]:
# Creating a one-dimensional array with 1000 samples drawn
# from a normal distribution
samples = np.random.normal(5, 1.5, 1000)

In [128]:
# Creating from a normal distribution
samples_2d = np.random.normal(5, 1.5, size=(5, 5))
samples_2d

array([[1.74924621, 7.45419839, 4.43699559, 5.91413008, 6.10340514],
       [7.50161365, 6.53405977, 2.59141374, 8.63804508, 2.41274865],
       [5.64104835, 7.14932188, 3.2021724 , 2.53053485, 6.87074725],
       [6.31962229, 3.18905625, 5.30346892, 6.8994307 , 5.44185957],
       [7.85464811, 4.00792303, 5.66690793, 6.11190731, 5.19042367]])

In [129]:
# mean(a, axis=None) returns the average of the array elements. The
# average is computed over the flattened array by default, otherwise
# over the specified axis.

In [130]:
# average(a, axis=None) returns the average of the array elements
# and works similar to that of mean().

In [131]:
# Computing mean
np.mean(samples)

np.float64(5.12989378374621)

In [132]:
np.average(samples)

np.float64(5.12989378374621)

In [133]:
# Computing mean with axis=1 (over each row)
np.mean(samples_2d, axis=1)

array([5.13159508, 5.53557618, 5.07876495, 5.43068755, 5.76636201])

In [134]:
np.average(samples_2d, axis=1)

array([5.13159508, 5.53557618, 5.07876495, 5.43068755, 5.76636201])

In [135]:
# max(a, axis=None) returns the maximum of an array or maximum along an axis.

In [139]:
np.max(samples)

np.float64(10.219773289479416)

In [138]:
np.max(samples_2d, axis=1)

array([7.45419839, 8.63804508, 7.14932188, 6.8994307 , 7.85464811])

In [141]:
# var(a, axis=None) returns the variance of an array or along the specified axis.

In [142]:
np.var(samples)

np.float64(2.325402405381643)

In [143]:
np.var(samples_2d)

np.float64(3.4861879919166716)

In [144]:
# The variance is computed over each column of numbers
np.var(samples_2d, axis=0)

array([4.76401424, 3.00717809, 1.40015245, 3.96471475, 2.28696429])

In [145]:
# std(a, axis=None) returns the standard deviation of an array or along the specified axis.

In [146]:
np.std(samples)

np.float64(1.524927016411488)

In [147]:
np.std(samples_2d)

np.float64(1.8671336299035137)

In [148]:
# sum(a, axis=None) returns the sum of array elements.

In [149]:
# Recalling the array n_put_vol
n_put_vol

array([52.89, 45.14, 63.84, 77.1 , 74.6 ])

In [150]:
# Computing sum of all elements within n_put_vol
np.sum(n_put_vol)

np.float64(313.57)

In [151]:
# Computing sum of all array over each row
np.sum(samples_2d, axis=1)

array([25.6579754 , 27.67788089, 25.39382474, 27.15343773, 28.83181004])

In [152]:
# cumsum(a, axis=None) returns the cumulative sum of the elements along a given axis.

In [153]:
np.cumsum(n_put_vol)

array([ 52.89,  98.03, 161.87, 238.97, 313.57])

In [154]:
# The methods discussed above can also be directly called upon NumPy ob-
# jects such as samples, n_put_vol, samples_2d, etc. instead of using the np.
# format as shown below. The output will be the same in both cases.

In [155]:
# Using np format to compute the sum
np.sum(samples)

np.float64(5129.89378374621)

In [156]:
# Calling sum() directly on a NumPy object 
samples.sum()

np.float64(5129.89378374621)

# 10.5 Array Manipulation

In [ ]:
# NumPy defines a new data type called ndarray for the array object it cre-
# ates. This also means that various operators such as arithmetic operators,
# logical operator, boolean operators, etc. work in ways unique to it as we’ve
# seen so far. There’s a flexible and useful array manipulation technique that
# NumPy provides to use on its data structure using broadcasting.

In [ ]:
# The term broadcasting describes how NumPy treats arrays with different
# shapes during arithmetic operations (with certain constraints). The smaller
# array is ’broadcast’ across the larger array so that they have compatible
# shapes. It also provides a mean of vectorizing array operations.

In [ ]:
# NumPy operations are usually done on pairs of arrays on an element-by-
# element basis. In the simplest case, the two arrays must have exactly the
# same shape as in the following example.

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([3, 3, 3])
a * b

array([3, 6, 9])

In [3]:
# NumPy’s broadcasting rule relaxes this constraint when the array’s shapes
# meet certain constraints. The simplest broadcasting example occurs when
# an array and a scalar value are combined in operation as depicted below:
a = np.array([1, 2, 3])
b = 3
a * b

array([3, 6, 9])

In [4]:
# The result is equivalent to the previous example where b was an array.
# We can think of the scalar b in the above example being stretched during
# the arithmetic operation into an array with the same shape as a. The
# new elements in b are simply copies of the original scalar. Here, the
# stretching analogy is only conceptual. NumPy is smart enough to use
# the original scalar value without actually making copies so that broad-
# casting operations are as memory and computationally efficient as possible.

In [5]:
# The code in the last example is more efficient because broadcasting moves
# less memory around during the multiplication than that of its counter-
# part defined above it. Along with efficient number processing capabili-
# ties, NumPy also provides various methods for array manipulation thereby
# proving versatility. We discuss some of them here.

In [6]:
# exp(*args) returns the exponential of all elements in the input array.
# The numbers will be raised to e also known as Euler’s number.

# Computing exponentials for the array 'a'
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [7]:
# sqrt(*args) returns the positive square-root of an array, element-wise.

# Computing square roots of a given array
np.sqrt([1, 4, 9, 16, 25])

array([1., 2., 3., 4., 5.])

In [8]:
# reshape(new_shape) gives a new shape to an array without changing its data.
res = np.arange(12)
res

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# Reshaping the 'res' array to 2-dimensional array
np.reshape(res, (3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
# resize(a, new_shape) return a new array with the specified shape.
# If the new array is larger than the original array, then the new array is
# filled with repeated copies of a.